apiVersion: v1
kind: Service
metadata:
  name: multi-nginx-svc
spec:
  type: NodePort
  selector:
    app: multi-nginx
  ports:
    - name: web80
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: web81
      port: 81
      targetPort: 81
      nodePort: 30081y
      